// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT3ySDEVeIIJ6m0TPreMGt1_ZP-mB8pDM',
    appId: '1:234169969165:web:699e81bf992f8008ec4344',
    messagingSenderId: '234169969165',
    projectId: 'pathwise-76e29',
    authDomain: 'pathwise-76e29.firebaseapp.com',
    storageBucket: 'pathwise-76e29.firebasestorage.app',
    measurementId: 'G-44T69NLF11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHdu-yca6KUG2ozVXduMyePHa5F09E8k',
    appId: '1:234169969165:android:e2857ccae1a5ab25ec4344',
    messagingSenderId: '234169969165',
    projectId: 'pathwise-76e29',
    storageBucket: 'pathwise-76e29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTZqEHqs1H98wj5hp_pPQuUDLFYz0mNSQ',
    appId: '1:234169969165:ios:672abe695c27dab4ec4344',
    messagingSenderId: '234169969165',
    projectId: 'pathwise-76e29',
    storageBucket: 'pathwise-76e29.firebasestorage.app',
    iosClientId: '234169969165-didtcdel84incdmmemkc3ndlca8sfhts.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTZqEHqs1H98wj5hp_pPQuUDLFYz0mNSQ',
    appId: '1:234169969165:ios:672abe695c27dab4ec4344',
    messagingSenderId: '234169969165',
    projectId: 'pathwise-76e29',
    storageBucket: 'pathwise-76e29.firebasestorage.app',
    iosClientId: '234169969165-didtcdel84incdmmemkc3ndlca8sfhts.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT3ySDEVeIIJ6m0TPreMGt1_ZP-mB8pDM',
    appId: '1:234169969165:web:0ea1901a32568cc3ec4344',
    messagingSenderId: '234169969165',
    projectId: 'pathwise-76e29',
    authDomain: 'pathwise-76e29.firebaseapp.com',
    storageBucket: 'pathwise-76e29.firebasestorage.app',
    measurementId: 'G-6ZSY3QMXPR',
  );

}